// Generated by commsdsl2tools_qt v7.0.3

#include "MsgFactory.h"

#include "cc_tools_qt_plugin/Message/cc_demo2/message/Msg1.h"
#include "cc_tools_qt_plugin/Message/cc_demo2/message/Msg2.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_demo2
{

namespace factory
{

MsgFactory::MsgFactory() = default;
MsgFactory::~MsgFactory() = default;

MsgFactory::MessagesListInternal MsgFactory::createAllMessagesImpl()
{
    return
        MessagesListInternal{
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_demo2::message::Msg1),
            cc_tools_qt::ToolsMessagePtr(new cc_tools_qt_plugin::Message::cc_demo2::message::Msg2)
        };
}

} // namespace factory

} // namespace cc_demo2

} // namespace Message

} // namespace cc_tools_qt_plugin
