// Generated by commsdsl2tools_qt v7.0.0

#include "Plugin_CC_Demo2.h"

#include "Protocol_CC_Demo2.h"

namespace cc_tools_qt_plugin
{

namespace cc_demo2
{

namespace plugin
{

Plugin_CC_Demo2::Plugin_CC_Demo2() :
    Base(Type_Protocol)
{
}

Plugin_CC_Demo2::~Plugin_CC_Demo2() = default;

cc_tools_qt::ToolsProtocolPtr Plugin_CC_Demo2::createProtocolImpl()
{
    return cc_tools_qt::ToolsProtocolPtr(new Protocol_CC_Demo2());
}

} // namespace plugin

} // namespace cc_demo2

} // namespace cc_tools_qt_plugin
