// Generated by commsdsl2tools_qt v7.1.0

#include "Protocol_CC_Demo2.h"

#include "cc_tools_qt_plugin/Message/cc_demo2/frame/Frame.h"

namespace cc_tools_qt_plugin
{

namespace cc_demo2
{

namespace plugin
{

Protocol_CC_Demo2::Protocol_CC_Demo2() :
    Base(std::make_unique<cc_tools_qt_plugin::Message::cc_demo2::frame::Frame>())
{
}

Protocol_CC_Demo2::~Protocol_CC_Demo2() = default;

const QString& Protocol_CC_Demo2::nameImpl() const
{
        static const QString Str("CC Demo2");
        return Str;
}

} // namespace plugin

} // namespace cc_demo2

} // namespace cc_tools_qt_plugin
