// Generated by commsdsl2tools_qt v7.0.3

/// @file
/// @brief Contains definition of the default options for plugin.

#pragma once

#include "cc_demo2/options/AllMessagesDynMemMsgFactoryDefaultOptions.h"
#include "cc_demo2/options/DefaultOptions.h"
#include "cc_tools_qt_plugin/cc_demo2/Version.h"

namespace cc_tools_qt_plugin
{

namespace cc_demo2
{

namespace options
{

using DefaultOptions =
    ::cc_demo2::options::AllMessagesDynMemMsgFactoryDefaultOptionsT<
        ::cc_demo2::options::DefaultOptions
    >;

} // namespace options

} // namespace cc_demo2

} // namespace cc_tools_qt_plugin
