// Generated by commsdsl2tools_qt v6.3.0

#pragma once

#include <tuple>
#include "cc_tools_qt_plugin/cc_demo2/message/Msg1.h"
#include "cc_tools_qt_plugin/cc_demo2/message/Msg2.h"

namespace cc_tools_qt_plugin
{

namespace cc_demo2
{

namespace input
{

using AllMessages =
    std::tuple<
        cc_tools_qt_plugin::cc_demo2::message::Msg1,
        cc_tools_qt_plugin::cc_demo2::message::Msg2
    >;

} // namespace input

} // namespace cc_demo2

} // namespace cc_tools_qt_plugin
